version: "3.9"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
    command: --api.insecure=true --providers.docker

  admin-install:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./src/admin:/app
    command: yarn

  perfume-admin:
    build:
      context: ./src/admin
      dockerfile: ../Dockerfile.dev
    restart: always
    depends_on:
      - admin-install
    volumes:
      - ./src/admin:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn dev --host 0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.perfume-admin.service=perfume-admin"
      - "traefik.http.routers.perfume-admin.rule=Host(`shop.localhost`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.perfume-admin.priority=100"
      - "traefik.http.services.perfume-admin.loadbalancer.server.port=5173"
    networks:
      - web

  shop-install:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./src/shop:/app
    command: yarn

  perfume-frontend:
    build:
      context: ./src/shop
      dockerfile: ../Dockerfile.dev
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - shop-install
    volumes:
      - ./src/shop:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.perfume-frontend.service=perfume-frontend"
      - "traefik.http.routers.perfume-frontend.rule=Host(`shop.localhost`)"
      - "traefik.http.routers.perfume-frontend.priority=10"
      - "traefik.http.services.perfume-frontend.loadbalancer.server.port=3000"
    networks:
      - web

volumes:
  node_shop:
  node_admin:

networks:
  web:
    external: true
