version: "3.9"
services:
  perfume-admin:
    image: xoriax/perfume-admin:latest
    container_name: perfume-admin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.perfume-admin.service=perfume-admin"
      - "traefik.http.routers.perfume-admin.rule=Host(`perfume.localhost`) && PathPrefix(`/admin`)"
      - "traefik.http.services.perfume-admin.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
