"""empty message

Revision ID: 19c2a70f63d1
Revises: 5be97f7b3f64
Create Date: 2024-07-18 04:02:21.201800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19c2a70f63d1'
down_revision: Union[str, None] = '5be97f7b3f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'cart_perfume', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'file', ['id'])
    op.create_unique_constraint(None, 'perfume', ['id'])
    op.create_unique_constraint(None, 'perfume_volume', ['id'])
    op.add_column('user', sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'update_time')
    op.drop_constraint(None, 'perfume_volume', type_='unique')
    op.drop_constraint(None, 'perfume', type_='unique')
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'cart_perfume', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    # ### end Alembic commands ###
