"""empty message

Revision ID: 7139480dc9ce
Revises: c127379cf708
Create Date: 2024-08-19 11:26:38.356641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7139480dc9ce'
down_revision: Union[str, None] = 'c127379cf708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfume_volume', sa.Column('cost', sa.Float(), nullable=False))
    op.drop_column('perfume_volume', 'const')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfume_volume', sa.Column('const', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('perfume_volume', 'cost')
    # ### end Alembic commands ###
