"""empty message

Revision ID: 7806e7183d0c
Revises: a749a6bf30d2
Create Date: 2024-07-18 12:31:44.853019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7806e7183d0c'
down_revision: Union[str, None] = 'a749a6bf30d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'delivery_date')
    # ### end Alembic commands ###
