"""empty message

Revision ID: 7f56ad7886e7
Revises: da7f23b59178
Create Date: 2024-07-21 19:40:55.903910

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '7f56ad7886e7'
down_revision: Union[str, None] = 'da7f23b59178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
