"""empty message

Revision ID: 9b88f58aef8d
Revises: 361dd705f75c
Create Date: 2024-07-19 09:57:58.866470

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b88f58aef8d'
down_revision: Union[str, None] = '361dd705f75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('pefume_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('favourite', sa.Column('perfume_id', sa.Uuid(), nullable=False))
    op.drop_constraint('favourite_perfume_volume_id_fkey', 'favourite', type_='foreignkey')
    op.create_foreign_key(None, 'favourite', 'perfume', ['perfume_id'], ['id'], ondelete='CASCADE')
    op.drop_column('favourite', 'perfume_volume_id')
    op.add_column('perfume', sa.Column('aroma', sa.String(), nullable=True))
    op.add_column('perfume', sa.Column('sex', sa.String(), nullable=False))
    op.add_column('perfume', sa.Column('brand_id', sa.Uuid(), nullable=True))
    op.add_column('perfume', sa.Column('perfume_type_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'perfume', 'brand', ['brand_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'perfume', 'pefume_type', ['perfume_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfume', type_='foreignkey')
    op.drop_constraint(None, 'perfume', type_='foreignkey')
    op.drop_column('perfume', 'perfume_type_id')
    op.drop_column('perfume', 'brand_id')
    op.drop_column('perfume', 'sex')
    op.drop_column('perfume', 'aroma')
    op.add_column('favourite', sa.Column('perfume_volume_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favourite', type_='foreignkey')
    op.create_foreign_key('favourite_perfume_volume_id_fkey', 'favourite', 'perfume_volume', ['perfume_volume_id'], ['id'], ondelete='CASCADE')
    op.drop_column('favourite', 'perfume_id')
    op.drop_table('pefume_type')
    op.drop_table('brand')
    # ### end Alembic commands ###
