"""empty message

Revision ID: a749a6bf30d2
Revises: 08c766de32ed
Create Date: 2024-07-18 05:38:10.058138

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a749a6bf30d2'
down_revision: Union[str, None] = '08c766de32ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'status', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status', type_='unique')
    # ### end Alembic commands ###
