"""empty message

Revision ID: c127379cf708
Revises: 83bfdd3b3176
Create Date: 2024-07-27 03:39:51.063701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c127379cf708'
down_revision: Union[str, None] = '83bfdd3b3176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brand', ['id'])
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'cart_perfume', ['id'])
    op.create_unique_constraint(None, 'file', ['url'])
    op.create_unique_constraint(None, 'file', ['id'])
    op.create_unique_constraint(None, 'perfume', ['id'])
    op.create_unique_constraint(None, 'perfume_type', ['id'])
    op.create_unique_constraint(None, 'perfume_volume', ['id'])
    op.create_unique_constraint(None, 'status', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'perfume_volume', type_='unique')
    op.drop_constraint(None, 'perfume_type', type_='unique')
    op.drop_constraint(None, 'perfume', type_='unique')
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_constraint(None, 'cart_perfume', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_constraint(None, 'brand', type_='unique')
    # ### end Alembic commands ###
