FROM node:alpine as base

WORKDIR /src
COPY package.json  .
COPY yarn.lock  .

RUN yarn

FROM base as build
WORKDIR /src
COPY . .

RUN yarn build

FROM nginx as runtime

COPY --from=build /src/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/dist /usr/share/nginx/html
